package main

import (
	"bytes"
	"flag"
	"fmt"
	"hash/fnv"
	"math"
	"os"
	"path"
	"reflect"
	"strconv"
	"strings"
	"unicode"

	"connectrpc.com/connect"
	"github.com/code-crafters-lab/ccl/pkg/extension"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	name       = "dict"
	pluginName = "protoc-gen-" + name
	version    = "0.1.0"

	usage = "learn how to use this plugin.\n\nFlags:\n  -h, --help\tPrint this help and exit.\n      --version\tPrint the version and exit."
)

type option struct {
	javaEnumPackage string
	outType         string
	markdown        bool
	sql             bool
	java            bool
}

func (o *option) phrase() {
	o.sql = o.support("sql")
	o.java = o.support("java")
	o.markdown = o.support("md")
}

func (o *option) support(typeName string) bool {
	return strings.Contains(o.outType, typeName)
}

var opts option

func main() {
	if len(os.Args) == 2 && os.Args[1] == "--version" {
		_, _ = fmt.Fprintln(os.Stdout, connect.Version)
		os.Exit(0)
	}
	if len(os.Args) == 2 && (os.Args[1] == "-h" || os.Args[1] == "--help") {
		_, _ = fmt.Fprintln(os.Stdout, usage)
		os.Exit(0)
	}
	if len(os.Args) != 1 {
		_, _ = fmt.Fprintln(os.Stderr, usage)
		os.Exit(1)
	}
	var flagSet flag.FlagSet
	flagSet.StringVar(&opts.javaEnumPackage, "java_enum_package", "", "java enum package")
	flagSet.StringVar(&opts.outType, "out_type", "", "Generate java,markdown,sql,go")
	protogen.Options{
		ParamFunc: flagSet.Set,
	}.Run(
		func(plugin *protogen.Plugin) error {
			plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL) | uint64(pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)
			plugin.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO2
			plugin.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024
			for _, file := range plugin.Files {
				if file.Generate {
					opts.phrase()
					generate(plugin, file, opts)
				}
			}
			return nil
		},
	)
}

func generate(plugin *protogen.Plugin, file *protogen.File, opts option) {
	// 1. 顶层枚举
	enums := make([]*protogen.Enum, len(file.Enums))
	for i, e := range file.Enums {
		enums[i] = e
	}

	// 2. 递归查找所有消息,获取嵌套枚举
	for _, msg := range file.Messages {
		collectEnums(msg, &enums)
	}

	if len(enums) == 0 {
		return
	}

	dictionaries := make([]*dict, 0)
	for _, enum := range enums {
		dictionaries = append(dictionaries, ofDict(enum.Desc))
	}

	// 代码生成
	generateMarkdown(dictionaries, plugin, file, opts)
	generateSQL(dictionaries, plugin, file, opts)
	generateJavaEnum(dictionaries, plugin, file, opts)
}

// 生成 java 枚举
func generateJavaEnum(dictionaries []*dict, plugin *protogen.Plugin, file *protogen.File, opts option) {
	if !opts.java {
		return
	}
	for _, dictionary := range dictionaries {
		options := file.Proto.GetOptions()
		var (
			javaPackage string
			filename    string
		)
		if options.JavaPackage != nil && *options.JavaPackage != "" {
			javaPackage = *options.JavaPackage
		}
		if opts.javaEnumPackage != "" {
			javaPackage = opts.javaEnumPackage
		}
		filename = fmt.Sprintf("src/main/java/%s/%s.java", strings.ReplaceAll(javaPackage, ".", "/"), dictionary.Code)
		g := plugin.NewGeneratedFile(filename, file.GoImportPath)
		g.P("package ", javaPackage, ";")
		g.P()
		imports := []string{"lombok.AllArgsConstructor", "lombok.Getter", "org.codecrafterslab.unity.dict.api.EnumDictItem"}
		for _, i := range imports {
			g.P("import ", i, ";")
		}
		g.P()
		g.P("/**")
		g.P(" * ", "<p>", dictionary.Name, "</p>")
		g.P(" * ", "<p>", "Code generated by ", pluginName, ". DO NOT EDIT!", "</p>")
		g.P(" * ", "<p>", "versions:", "</p>")
		l := int(math.Max(float64(len(pluginName)), 6))
		g.P(" * ", "<p>", fmt.Sprintf("- %-*s \tv%s", l, pluginName, version), "</p>")
		protocVersion := protocVersion(plugin)
		if protocVersion != "" {
			g.P(" * ", "<p>", fmt.Sprintf("- %-*s \tv%s", l, "protoc", protocVersion), "</p>")
		}
		if file.Proto.GetOptions().GetDeprecated() {
			g.P(" * ", "<p>", file.Desc.Path(), " is a deprecated file.", "</p>")
		} else {
			g.P(" * ", "<p>", "source: ", file.Desc.Path(), "</p>")
		}
		g.P(" */")
		g.P("@Getter")
		g.P("@AllArgsConstructor")
		genericType := "Integer"
		if dictionary.ValueType == ValueTypeString {
			genericType = "String"
		}
		g.P(fmt.Sprintf("public enum %s implements EnumDictItem<%s> {", dictionary.Code, genericType))
		g.P()
		for _, item := range dictionary.Items {
			switch dictionary.ValueType {
			case ValueTypeString:
				g.P(fmt.Sprintf(`	%s("%s", "%s"),`, item.Code, item.Value, item.Name))
			case ValueTypeNumber:
				g.P(fmt.Sprintf(`	%s(%s, "%s"),`, item.Code, item.Value, item.Name))
			}
		}
		g.P()
		g.P("	;")
		g.P()
		g.P("	private final ", genericType, " value;")
		g.P("	private final String label;")
		g.P()
		g.P("}")
	}
}

// 生成 sql
func generateSQL(dictionaries []*dict, plugin *protogen.Plugin, file *protogen.File, opts option) {
	if !opts.sql {
		return
	}
	filename := fmt.Sprintf("%s.dict.sql", file.GeneratedFilenamePrefix)
	if opts.java {
		filename = fmt.Sprintf("%s.dict.sql", path.Base(file.GeneratedFilenamePrefix))
	}
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	generatePreamble(g, "-- ", file, plugin)

	for i, dictionary := range dictionaries {
		g.P()
		g.P(fmt.Sprintf("-- %d. %s", i+1, dictionary.Name))
		// 字典插入

		g.P(fmt.Sprintf("INSERT INTO %s (id, code, name, value_type, description) VALUES (%s);", "sys_dict", resolveDictValues(*dictionary)))
		// 字典项插入
		g.P(fmt.Sprintf("INSERT INTO %s (id, dict_id, code, name, value, sort, description)", "sys_dict_item"))
		for j, item := range dictionary.Items {
			var (
				placeholder = "VALUES"
				sep         = ","
			)
			if j > 0 {
				placeholder = ""
			}
			if j == len(dictionary.Items)-1 {
				sep = ";"
			}

			values := resolveItemValues(dictionary.ID, *item)
			g.P(fmt.Sprintf("%6s (%s)%s", placeholder, values, sep))
		}
	}
}

func resolveDictValues(dict dict) string {
	vals := []any{dict.ID, dict.FullCode, dict.Name, dict.ValueType, dict.Description}
	values := make([]string, len(vals))
	for i, v := range vals {
		values[i] = resolveValue(reflect.ValueOf(v), nil)
	}
	return strings.Join(values, ", ")
}

func resolveItemValues(dictId uint64, item dictItem) string {
	vals := []any{item.ID, dictId, item.Code, item.Name, item.Value, item.Sort, item.Description}
	values := make([]string, len(vals))
	for i, v := range vals {
		values[i] = resolveValue(reflect.ValueOf(v), nil)
	}
	return strings.Join(values, ", ")
}

func resolveValue(value reflect.Value, defaultVale interface{}) string {
	var result string
	switch value.Kind() {
	case reflect.Invalid:
		def := reflect.ValueOf(defaultVale)
		if def.Kind() == reflect.Invalid {
			result = "null"
		} else {
			result = resolveValue(def, nil)
		}
	case reflect.String:
		// todo 增加特殊字符串转义处理函数配置
		v := strings.ReplaceAll(strings.TrimSpace(value.String()), "'", "\\'")
		if v == "" {
			result = "null"
		} else {
			result = fmt.Sprintf("'%s'", v)
		}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		result = fmt.Sprintf("%d", value.Int())
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		result = fmt.Sprintf("%d", value.Uint())
	case reflect.Float32, reflect.Float64:
		result = fmt.Sprintf("%f", value.Float())
	default:
		result = "null"
	}
	return fmt.Sprintf("%s", result)
}

// 生成 markdown
func generateMarkdown(dictionaries []*dict, plugin *protogen.Plugin, file *protogen.File, opts option) {
	if !opts.markdown {
		return
	}
	filename := fmt.Sprintf("%s.dict.md", file.GeneratedFilenamePrefix)
	if opts.java {
		filename = fmt.Sprintf("%s.dict.md", path.Base(file.GeneratedFilenamePrefix))
	}
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	buf := bytes.Buffer{}
	for i, d := range dictionaries {
		buf.WriteString(fmt.Sprintf("## %d. %s\n", i+1, d.Name))
		buf.WriteByte('\n')
		buf.WriteString(fmt.Sprintf("- 字典编码：%s\n", d.FullCode))
		if d.Description != "" {
			buf.WriteString(fmt.Sprintf("- 字典编码：%s\n", d.Description))
		}
		buf.WriteByte('\n')

		buf.WriteString("| 名称 | 编码 | 值 | 排序 | 描述 |\n")
		buf.WriteString("| ---- | ---- | :----: | :----: | ---- |\n")
		for _, item := range d.Items {
			buf.WriteString(fmt.Sprintf("| %s | %v | %s | %d | %s |\n", item.Name, item.Code, item.Value, item.Sort, item.Description))
		}
	}

	_, _ = g.Write(buf.Bytes())
}

func collectEnums(msg *protogen.Message, enums *[]*protogen.Enum) {
	for _, e := range msg.Enums {
		*enums = append(*enums, e)
	}
	for _, m := range msg.Messages {
		collectEnums(m, enums)
	}
}

func protocVersion(plugin *protogen.Plugin) string {
	v := plugin.Request.GetCompilerVersion()
	if v == nil {
		return ""
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func generatePreamble(g *protogen.GeneratedFile, noteSymbol string, file *protogen.File, plugin *protogen.Plugin) {
	g.P(noteSymbol, "Code generated by ", pluginName, ". DO NOT EDIT!")
	g.P(noteSymbol, "versions:")
	l := int(math.Max(float64(len(pluginName)), 6))
	g.P(noteSymbol, fmt.Sprintf("- %-*s \tv%s", l, pluginName, version))
	protocVersion := protocVersion(plugin)
	if protocVersion != "" {
		g.P(noteSymbol, fmt.Sprintf("- %-*s \tv%s", l, "protoc", protocVersion))
	}
	if file.Proto.GetOptions().GetDeprecated() {
		g.P(noteSymbol, file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P(noteSymbol, "source: ", file.Desc.Path())
	}
}

type ValueType string

const (
	ValueTypeString = "S"
	ValueTypeNumber = "N"
)

type dict struct {
	ValueType   ValueType   `json:"value_type"`
	ID          uint64      `json:"id"`
	Code        string      `json:"code"`
	FullCode    string      `json:"full_code"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Items       []*dictItem `json:"items"`
}

type dictItem struct {
	zero        bool
	valueType   ValueType
	ID          uint64 `json:"id"`
	Code        string `json:"code"`
	Value       string `json:"value"`
	Name        string `json:"name"`
	Sort        int    `json:"sort"`
	Description string `json:"description"`
}

func (i dictItem) IsZero() bool {
	return i.zero
}

func ofDict(enumDesc protoreflect.EnumDescriptor) *dict {
	d := &dict{
		ValueType: ValueTypeNumber,
		Code:      string(enumDesc.Name()),
		FullCode:  string(enumDesc.FullName()),
	}
	// 2. 读取 enum 级别（EnumOptions）的扩展
	enumOptions := enumDesc.Options()
	if proto.HasExtension(enumOptions, extension.E_Dict) {
		ext := proto.GetExtension(enumOptions, extension.E_Dict)
		metadata := ext.(*extension.DictExtensionMetadata)
		if metadata.Name != nil {
			d.Name = *metadata.Name
		}
		if metadata.Description != nil {
			d.Description = *metadata.Description
		}
	}
	// 字典唯一 id 生成
	d.ID = strToNumFNV64(d.FullCode)
	// 字典项数据
	items := ofDictItems(enumDesc, d.ID, "其他（默认值）")
	// 字典值类型
	d.ValueType = valueTypeOf(items)
	d.Items = items
	return d
}

// 字符串转64位数字（FNV-1a哈希）
func strToNumFNV64(s string) uint64 {
	h := fnv.New64a() // 创建64位FNV-1a哈希器
	_, _ = h.Write([]byte(s))
	return h.Sum64() // 返回64位哈希值（uint64）
}

func valueTypeOf(items []*dictItem) ValueType {
	for _, item := range items {
		if item.valueType == ValueTypeString {
			return ValueTypeString
		}
	}
	return ValueTypeNumber
}

func ofDictItems(enumDesc protoreflect.EnumDescriptor, did uint64, defaultUnspecifiedName string) []*dictItem {
	valueDescriptors := enumDesc.Values()
	items := make([]*dictItem, 0)

	for j := range valueDescriptors.Len() {
		enumValueDesc := valueDescriptors.Get(j)

		item := &dictItem{
			Code:      replaceEnumPrefix(string(enumValueDesc.Name()), enumDesc.Name()),
			Value:     strconv.Itoa(int(enumValueDesc.Number())),
			valueType: ValueTypeNumber,
			Sort:      enumValueDesc.Index(),
		}

		item.ID = strToNumFNV64(fmt.Sprintf("%d_%s", did, item.Code))

		if enumValueDesc.Number() == 0 {
			item.zero = true
			item.Name = defaultUnspecifiedName
		}

		enumValueOptions := enumValueDesc.Options()
		options := enumValueOptions.(*descriptorpb.EnumValueOptions)
		if options != nil {
			deprecated := options.Deprecated != nil && *options.Deprecated
			if deprecated {
				item.Description = "已废弃"
			}
			if proto.HasExtension(enumValueOptions, extension.E_Item) {
				valExt := proto.GetExtension(enumValueOptions, extension.E_Item)
				itemMetadata := valExt.(*extension.DictItemExtensionMetadata)
				if deprecated && itemMetadata.ReplaceWith != nil && *itemMetadata.ReplaceWith != "" {
					item.Description += " (请使用 " + replaceEnumPrefix(*itemMetadata.ReplaceWith, enumDesc.Name()) + " 代替)"
				}
				if itemMetadata.Name != nil && *itemMetadata.Name != "" {
					item.Name = *itemMetadata.Name
				}
				if itemMetadata.Value != nil && *itemMetadata.Value != "" {
					item.Value = *itemMetadata.Value
					item.valueType = ValueTypeString
				}
				if itemMetadata.Description != nil {
					description := item.Description
					if description != "" {
						item.Description += ";" + *itemMetadata.Description
					} else {
						item.Description = *itemMetadata.Description
					}
				}
			}
		}

		items = append(items, item)

	}

	return items
}

func replaceEnumPrefix(code string, name protoreflect.Name) string {
	prefix := CamelToSnakeUpper(string(name))
	return strings.TrimLeft(strings.Replace(code, prefix, "", 1), "_")
}

// CamelToSnakeUpper converts a CamelCase string to SNAKE_CASE_UPPER.
func CamelToSnakeUpper(s string) string {
	if s == "" {
		return ""
	}

	var builder strings.Builder
	// 预留足够的容量，避免多次内存分配
	builder.Grow(len(s) + 4) // 预估最多会增加4个下划线

	for i, r := range s {
		// 如果是大写字母，并且满足以下条件之一，则在前面添加下划线：
		// 1. 不是第一个字符。
		// 2. 前一个字符不是下划线。
		// 3. 后一个字符是小写字母（处理 "HTTPRequest" -> "HTTP_REQUEST" 的情况）。
		// 4. 前一个字符是小写字母（处理 "MyID" -> "MY_ID" 的情况）。
		if unicode.IsUpper(r) {
			if i > 0 && s[i-1] != '_' &&
				((i+1 < len(s) && unicode.IsLower(rune(s[i+1]))) || unicode.IsLower(rune(s[i-1]))) {
				builder.WriteRune('_')
			}
		}
		builder.WriteRune(r)
	}

	return strings.ToUpper(builder.String())
}
