edition = "2023";

option go_package = "github.com/code-crafters-lab/idl/resources";
option java_package = "org.ccl.resources";
option java_outer_classname = "RouteProto";
option java_multiple_files = true;

package resources;

import "auth/authority.proto";
import "auth/data_access.proto";
import "auth/operation.proto";
import "resources/app.proto";
import "resources/menu.proto";
import "resources/route/api.proto";
import "resources/route/link.proto";
import "resources/route/page.proto";

/**
 * 资源类型
 */
enum ResourceType {
    // 系统（应用）资源
    RESOURCE_TYPE_APP = 0;
    // 菜单资源
    RESOURCE_TYPE_MENU = 1;
    // 操作资源
    RESOURCE_TYPE_OPERATION = 2;
    // 数据资源
    RESOURCE_TYPE_DATA_ACCESS = 3;
    // 接口资源
    RESOURCE_TYPE_API = 4;
    // 外链资源
    RESOURCE_TYPE_EXTERNAL_LINK = 5;
    // 页面资源
    RESOURCE_TYPE_PAGE = 6;
}













