edition = "2023";

package authorization;

/* 注册文件信息 */
message Registration {
    message Information {
        string machine_code = 1 [json_name = "machinecode"];
        string mac_address = 2 [json_name = "macaddress"];
        string app_name = 3 [json_name = "appname"];
        string version = 4 [json_name = "version"];
        string vendor = 5 [json_name = "vendor"];
    }

    oneof content {
        bytes raw = 1;
        Information data = 2;
    }

    string content_hash = 3;
}

message GenerateLicenseRequest {
    // 注册信息
    Registration registration = 1;

    // 访问令牌
    string access_token = 2;

    // 动态密码
    string code = 3;
}

message License {
    // 文件名称(不含扩展名)
    string file_name = 1;
    // 文件扩展名
    string file_ext = 2;
    // 授权截止时间
    string deadline = 3;
    // 授权内容
    bytes file_contents = 4;
    // 注册文件签名
    string registration_sign = 5;
}

message GenerateLicenseResponse {
    bool success = 1;
    oneof result {
        // 如果成功，返回许可证
        License license = 2;
        // 如果失败，返回错误信息
        string error_message = 3;
    }
}

service LicenseService {
    // 生成许可证
    rpc Generate (GenerateLicenseRequest) returns (GenerateLicenseResponse) {}
}