// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: extension/authority.proto

package extension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 权限元数据：定义单个权限（对应二进制中的一位）
type AuthorityExtensionMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限唯一标识（如"read"、"write"，需全局唯一）
	Code *string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// 权限描述（如"读取资源"）
	Description *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// 对应二进制位的索引（从 0 开始，如 0 → 第0位 → 2^0=1）
	BitIndex *uint64 `protobuf:"varint,3,opt,name=bit_index,json=bitIndex" json:"bit_index,omitempty"`
	// 对应十进制值（2^bit_index，如bit_index=0→1，bit_index=1→2）
	DecimalValue *string `protobuf:"bytes,4,opt,name=decimal_value,json=decimalValue" json:"decimal_value,omitempty"`
	// 对应十六进制值（2^bit_index，如bit_index=0→1，bit_index=1→2）
	HexValue      *string `protobuf:"bytes,5,opt,name=hex_value,json=hexValue" json:"hex_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorityExtensionMetadata) Reset() {
	*x = AuthorityExtensionMetadata{}
	mi := &file_extension_authority_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityExtensionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityExtensionMetadata) ProtoMessage() {}

func (x *AuthorityExtensionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_extension_authority_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityExtensionMetadata.ProtoReflect.Descriptor instead.
func (*AuthorityExtensionMetadata) Descriptor() ([]byte, []int) {
	return file_extension_authority_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorityExtensionMetadata) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *AuthorityExtensionMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AuthorityExtensionMetadata) GetBitIndex() uint64 {
	if x != nil && x.BitIndex != nil {
		return *x.BitIndex
	}
	return 0
}

func (x *AuthorityExtensionMetadata) GetDecimalValue() string {
	if x != nil && x.DecimalValue != nil {
		return *x.DecimalValue
	}
	return ""
}

func (x *AuthorityExtensionMetadata) GetHexValue() string {
	if x != nil && x.HexValue != nil {
		return *x.HexValue
	}
	return ""
}

var file_extension_authority_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthorityExtensionMetadata)(nil),
		Field:         1001,
		Name:          "ccl.authority",
		Tag:           "bytes,1001,opt,name=authority",
		Filename:      "extension/authority.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// 权限控制
	//
	// optional ccl.AuthorityExtensionMetadata authority = 1001;
	E_Authority = &file_extension_authority_proto_extTypes[0]
)

var File_extension_authority_proto protoreflect.FileDescriptor

const file_extension_authority_proto_rawDesc = "" +
	"\n" +
	"\x19extension/authority.proto\x12\x03ccl\x1a google/protobuf/descriptor.proto\"\xb1\x01\n" +
	"\x1aAuthorityExtensionMetadata\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tbit_index\x18\x03 \x01(\x04R\bbitIndex\x12#\n" +
	"\rdecimal_value\x18\x04 \x01(\tR\fdecimalValue\x12\x1b\n" +
	"\thex_value\x18\x05 \x01(\tR\bhexValue:^\n" +
	"\tauthority\x12\x1e.google.protobuf.MethodOptions\x18\xe9\a \x01(\v2\x1f.ccl.AuthorityExtensionMetadataR\tauthorityBu\n" +
	"\acom.cclB\x0eAuthorityProtoP\x01Z.github.com/code-crafters-lab/ccl/pkg/extension\xa2\x02\x03CXX\xaa\x02\x03Ccl\xca\x02\x03Ccl\xe2\x02\x0fCcl\\GPBMetadata\xea\x02\x03Cclb\beditionsp\xe8\a"

var (
	file_extension_authority_proto_rawDescOnce sync.Once
	file_extension_authority_proto_rawDescData []byte
)

func file_extension_authority_proto_rawDescGZIP() []byte {
	file_extension_authority_proto_rawDescOnce.Do(func() {
		file_extension_authority_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_authority_proto_rawDesc), len(file_extension_authority_proto_rawDesc)))
	})
	return file_extension_authority_proto_rawDescData
}

var file_extension_authority_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extension_authority_proto_goTypes = []any{
	(*AuthorityExtensionMetadata)(nil), // 0: ccl.AuthorityExtensionMetadata
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_extension_authority_proto_depIdxs = []int32{
	1, // 0: ccl.authority:extendee -> google.protobuf.MethodOptions
	0, // 1: ccl.authority:type_name -> ccl.AuthorityExtensionMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extension_authority_proto_init() }
func file_extension_authority_proto_init() {
	if File_extension_authority_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_authority_proto_rawDesc), len(file_extension_authority_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_extension_authority_proto_goTypes,
		DependencyIndexes: file_extension_authority_proto_depIdxs,
		MessageInfos:      file_extension_authority_proto_msgTypes,
		ExtensionInfos:    file_extension_authority_proto_extTypes,
	}.Build()
	File_extension_authority_proto = out.File
	file_extension_authority_proto_goTypes = nil
	file_extension_authority_proto_depIdxs = nil
}
