// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: extension/dict.proto

package extension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DictExtensionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ReplaceWith   *string                `protobuf:"bytes,4,opt,name=replace_with,json=replaceWith" json:"replace_with,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictExtensionMetadata) Reset() {
	*x = DictExtensionMetadata{}
	mi := &file_extension_dict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictExtensionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictExtensionMetadata) ProtoMessage() {}

func (x *DictExtensionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_extension_dict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictExtensionMetadata.ProtoReflect.Descriptor instead.
func (*DictExtensionMetadata) Descriptor() ([]byte, []int) {
	return file_extension_dict_proto_rawDescGZIP(), []int{0}
}

func (x *DictExtensionMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DictExtensionMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *DictExtensionMetadata) GetReplaceWith() string {
	if x != nil && x.ReplaceWith != nil {
		return *x.ReplaceWith
	}
	return ""
}

var file_extension_dict_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1001,
		Name:          "ccl.dict_enable",
		Tag:           "varint,1001,opt,name=dict_enable,def=0",
		Filename:      "extension/dict.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*DictExtensionMetadata)(nil),
		Field:         1001,
		Name:          "ccl.dict",
		Tag:           "bytes,1001,opt,name=dict",
		Filename:      "extension/dict.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*DictExtensionMetadata)(nil),
		Field:         1001,
		Name:          "ccl.item",
		Tag:           "bytes,1001,opt,name=item",
		Filename:      "extension/dict.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional bool dict_enable = 1001;
	E_DictEnable = &file_extension_dict_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional ccl.DictExtensionMetadata dict = 1001;
	E_Dict = &file_extension_dict_proto_extTypes[1]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional ccl.DictExtensionMetadata item = 1001;
	E_Item = &file_extension_dict_proto_extTypes[2]
)

var File_extension_dict_proto protoreflect.FileDescriptor

const file_extension_dict_proto_rawDesc = "" +
	"\n" +
	"\x14extension/dict.proto\x12\x03ccl\x1a google/protobuf/descriptor.proto\"|\n" +
	"\x15DictExtensionMetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\freplace_with\x18\x04 \x01(\tR\vreplaceWithJ\x04\b\x01\x10\x02R\x04code:E\n" +
	"\vdict_enable\x12\x1c.google.protobuf.FileOptions\x18\xe9\a \x01(\b:\x05falseR\n" +
	"dictEnable:M\n" +
	"\x04dict\x12\x1c.google.protobuf.EnumOptions\x18\xe9\a \x01(\v2\x1a.ccl.DictExtensionMetadataR\x04dict:R\n" +
	"\x04item\x12!.google.protobuf.EnumValueOptions\x18\xe9\a \x01(\v2\x1a.ccl.DictExtensionMetadataR\x04itemBp\n" +
	"\acom.cclB\tDictProtoP\x01Z.github.com/code-crafters-lab/ccl/pkg/extension\xa2\x02\x03CXX\xaa\x02\x03Ccl\xca\x02\x03Ccl\xe2\x02\x0fCcl\\GPBMetadata\xea\x02\x03Cclb\beditionsp\xe8\a"

var (
	file_extension_dict_proto_rawDescOnce sync.Once
	file_extension_dict_proto_rawDescData []byte
)

func file_extension_dict_proto_rawDescGZIP() []byte {
	file_extension_dict_proto_rawDescOnce.Do(func() {
		file_extension_dict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_dict_proto_rawDesc), len(file_extension_dict_proto_rawDesc)))
	})
	return file_extension_dict_proto_rawDescData
}

var file_extension_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extension_dict_proto_goTypes = []any{
	(*DictExtensionMetadata)(nil),         // 0: ccl.DictExtensionMetadata
	(*descriptorpb.FileOptions)(nil),      // 1: google.protobuf.FileOptions
	(*descriptorpb.EnumOptions)(nil),      // 2: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 3: google.protobuf.EnumValueOptions
}
var file_extension_dict_proto_depIdxs = []int32{
	1, // 0: ccl.dict_enable:extendee -> google.protobuf.FileOptions
	2, // 1: ccl.dict:extendee -> google.protobuf.EnumOptions
	3, // 2: ccl.item:extendee -> google.protobuf.EnumValueOptions
	0, // 3: ccl.dict:type_name -> ccl.DictExtensionMetadata
	0, // 4: ccl.item:type_name -> ccl.DictExtensionMetadata
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extension_dict_proto_init() }
func file_extension_dict_proto_init() {
	if File_extension_dict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_dict_proto_rawDesc), len(file_extension_dict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_extension_dict_proto_goTypes,
		DependencyIndexes: file_extension_dict_proto_depIdxs,
		MessageInfos:      file_extension_dict_proto_msgTypes,
		ExtensionInfos:    file_extension_dict_proto_extTypes,
	}.Build()
	File_extension_dict_proto = out.File
	file_extension_dict_proto_goTypes = nil
	file_extension_dict_proto_depIdxs = nil
}
