edition = "2023";

option go_package = "github.com/code-crafters-lab/ccl/pkg/grpc/resources";

package ccl.resources;

import "ccl/authority/metadata.proto";
import "ccl/resources/route.proto";

// 菜单资源
message Menu {
    // 菜单 ID
    string id = 1;
    // 父级菜单 ID
    string pid = 2;
    // 菜单名称
    string name = 3;
    // 菜单权限标识
    ccl.authority.AuthorityMetadata authority_metadata = 4;
    // 菜单图标
    string icon = 5;
    // 菜单排序
    int32 sort = 6;
    // 菜单描述
    string description = 7;
//    // 页面路由或外链路由
//    Route route = 8;
//    // 子菜单列表
//    repeated Menu sub_menus = 9;
//    // 父菜单
//    Menu parent_menu = 10;
}







